version: "3.8"
services:
    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
        volumes:
            - mongodb-data:/data/db
        ports:
            - "27017:27017"
        restart: on-failure

volumes:
    mongodb-data:
